### ISSUE TITLE
 left/right buffer swapping stereo option

### ISSUE THREAD

**Issue by andreasplesch** [nasa/DERT#5]
Ardor3d seems to support quad-buffered stereo as a stereo mode for the camera. May I suggest to add this mode as an option ? Although I am not very fluent in java, I could give this a try if there is no interest at Nasa.

Also, there is a Ardor3d anaglyph stereo mode but here may be a reason why a custom anaglyph mode is used ?

**Comment by lekeely** [comment]
A hardware stereo option is desirable but is not provided in DERT because we currently have no way to test it.

The AnaglyphCamera class was created from a combination of the Ardor3D StereoCamera and the Ardor3D StereoExample classes.  DERT uses an extended Camera called BasicCamera so I couldn't use StereoCamera directly.  I didn't find the anaglyph stereo mode you speak of.  Perhaps you can point me to the code?

Thank you for your good ideas and feedback.

**Comment by andreasplesch** [comment]
Thanks for responding so quickly.

Yes, active stereo with shutter glasses seems to become a rare setup, even at Nasa centers it seems.

I looked at the Ardor3d stereo example:

https://github.com/Renanse/Ardor3D/blob/master/ardor3d-examples/src/main/java/com/ardor3d/example/renderer/StereoExample.java

which has an example implementation of anaglyph mode (and side by side mode) to be adopted. But you are correct the library itself does not have the option.
